# Generated by Django 6.1 on 2026-08-19 18:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_articlepage_homepage_hero_image_homepage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='body_stream',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {})}),
        ),
    ]
